# permissions for end users to edit indices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: index-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: es-provisioner-operator
    app.kubernetes.io/part-of: es-provisioner-operator
    app.kubernetes.io/managed-by: kustomize
  name: index-editor-role
rules:
- apiGroups:
  - es-provisioner.com.ramos
  resources:
  - indices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es-provisioner.com.ramos
  resources:
  - indices/status
  verbs:
  - get
